import { type SeverityCount, type Asset } from "@/constants";

export const severitySummary: SeverityCount = {
  critical: 3,
  high: 3,
  medium: 1,
  low: 1,
};

export const severityChartData = [
  { label: "Critical", value: severitySummary.critical, color: "#7F1D1D" },
  { label: "High", value: severitySummary.high, color: "#FF708B" },
  { label: "Medium", value: severitySummary.medium, color: "#FFBA69" },
  { label: "Low", value: severitySummary.low, color: "#006C50" },
];

export const severities = [
  {
    label: "Critical",
    value: severitySummary.critical,
    color: "#BA0001",
    bg: "rgba(186, 0, 1, 0.1)",
  },
  {
    label: "High",
    value: severitySummary.high,
    color: "#FF2D2E",
    bg: "rgba(255, 45, 46, 0.1)",
  },
  {
    label: "Medium",
    value: severitySummary.medium,
    color: "#FAA24B",
    bg: "rgba(250, 162, 75, 0.1)",
  },
  {
    label: "Low",
    value: severitySummary.low,
    color: "#53CA43",
    bg: "rgba(83, 202, 67, 0.1)",
  },
];

export const topAssets: Asset[] = [
  {
    name: "D.G. ASUNTOS LEGALES",
    severity: { critical: 3, high: 3, medium: 1, low: 0 },
  },
  {
    name: "D.G. CLIENTE",
    severity: { critical: 2, high: 2, medium: 3, low: 0 },
  },
  {
    name: "D.G. E&P",
    severity: { critical: 2, high: 2, medium: 42, low: 0 },
  },
  {
    name: "D.G. E&P",
    severity: { critical: 2, high: 2, medium: 42, low: 0 },
  },
  {
    name: "D.G. FINANZAS",
    severity: { critical: 1, high: 4, medium: 2, low: 0 },
  },
  {
    name: "D.G. TECNOLOGÍA",
    severity: { critical: 2, high: 1, medium: 5, low: 0 },
  },
  {
    name: "D.G. RECURSOS HUMANOS",
    severity: { critical: 2, high: 1, medium: 3, low: 0 },
  },
  {
    name: "D.G. OPERACIONES",
    severity: { critical: 1, high: 3, medium: 2, low: 0 },
  },
  {
    name: "D.G. COMERCIAL",
    severity: { critical: 1, high: 2, medium: 1, low: 0 },
  },
];

export const findings = [
  {
    id: 1,
    finding: "CVE-2024-4741",
    asset: { name: "AP_CORP_PORTAL", logo: "/ap_corp.png" },
    software:
      "La vulnerabilidad asociada con el Sling default POST Servlet enabled implica...",
    owner: { name: "Pedro Pablo Casandra", avatar: "/avatars/pedro.png" },
    internetStatus: "Exposed",
    status: "Assigned",
    severity: "Critical",
    source: "SOC",
    firstSeen: "21/12/2023 23:34:02",
    lastSeen: "12 Oct 2024 23:34:02",
    riskLevel: "Critical",
    responsibility: "SOC",
    resolvingGroup: "DevSecOps",
    businessUnit: "BU1",
    criticalAsset: true,
    regulation: "Reg1",
    riskState: "Open",
  },
  {
    id: 2,
    finding: "CVE-2024-4742",
    asset: { name: "AP_CORP_PORTAL", logo: "/ap_corp.png" },
    software:
      "La vulnerabilidad asociada con el Sling default POST Servlet enabled implica...",
    owner: { name: "Pedro Pablo Casandra", avatar: "/avatars/pedro.png" },
    internetStatus: "Locked",
    status: "Accepted",
    severity: "Critical",
    source: "Hacking",
    firstSeen: "21/12/2023 23:34:02",
    lastSeen: "12 Oct 2024 23:34:02",
    riskLevel: "Critical",
    responsibility: "Hacking",
    resolvingGroup: "DevSecOps",
    businessUnit: "BU1",
    criticalAsset: true,
    regulation: "Reg1",
    riskState: "Open",
  },
  {
    id: 3,
    finding: "CVE-2024-4743",
    asset: { name: "AP_CORP_PORTAL", logo: "/ap_corp.png" },
    software:
      "La vulnerabilidad asociada con el Sling default POST Servlet enabled implica...",
    owner: { name: "Pedro Pablo Casandra", avatar: "/avatars/pedro.png" },
    internetStatus: "Activated",
    status: "Unassigned",
    severity: "High",
    source: "DevSecOps",
    firstSeen: "12 Oct 2024 23:34:02",
    lastSeen: "12 Oct 2024 23:34:02",
    riskLevel: "High",
    responsibility: "DevSecOps",
    resolvingGroup: "Hacking",
    businessUnit: "BU2",
    criticalAsset: false,
    regulation: "Reg2",
    riskState: "Closed",
  },
  {
    id: 4,
    finding: "CVE-2024-5001",
    asset: { name: "SAP System", logo: "/sap.png" },
    software:
      "SAP NetWeaver AS JAVA (LM Configuration Wizard) has a missing authorization check vulnerability.",
    owner: { name: "Ana Gómez", avatar: "/avatars/ana.png" },
    internetStatus: "None",
    status: "Assigned",
    severity: "High",
    source: "SOC",
    firstSeen: "10 Oct 2024 09:12:45",
    lastSeen: "12 Oct 2024 10:15:00",
    riskLevel: "High",
    responsibility: "SOC",
    resolvingGroup: "DevSecOps",
    businessUnit: "BU2",
    criticalAsset: true,
    regulation: "Reg2",
    riskState: "Open",
  },
  {
    id: 5,
    finding: "CVE-2024-5002",
    asset: { name: "SAP System", logo: "/sap.png" },
    software:
      "SAP BusinessObjects has an information disclosure vulnerability due to improper access control.",
    owner: { name: "Luis Martínez", avatar: "/avatars/luis.png" },
    internetStatus: "Exposed",
    status: "Ignored",
    severity: "Medium",
    source: "DevSecOps",
    firstSeen: "05 Oct 2024 14:22:10",
    lastSeen: "11 Oct 2024 16:45:30",
    riskLevel: "Medium",
    responsibility: "DevSecOps",
    resolvingGroup: "Hacking",
    businessUnit: "BU1",
    criticalAsset: false,
    regulation: "Reg1",
    riskState: "Open",
  },
  {
    id: 6,
    finding: "CVE-2024-5003",
    asset: { name: "AP_PORTAL_TA", logo: "/ap_corp.png" },
    software:
      "AP_PORTAL_TA is vulnerable to cross-site scripting due to improper input validation.",
    owner: { name: "Maria Lopez", avatar: "/avatars/maria.png" },
    internetStatus: "None",
    status: "Unassigned",
    severity: "Low",
    source: "Hacking",
    firstSeen: "01 Oct 2024 08:00:00",
    lastSeen: "10 Oct 2024 12:00:00",
    riskLevel: "Low",
    responsibility: "Hacking",
    resolvingGroup: "DevSecOps",
    businessUnit: "BU2",
    criticalAsset: false,
    regulation: "Reg2",
    riskState: "Closed",
  },
  {
    id: 7,
    finding: "CVE-2024-5004",
    asset: { name: "SAP System", logo: "/sap.png" },
    software:
      "SAP Solution Manager has a directory traversal vulnerability allowing unauthorized file access.",
    owner: { name: "Carlos Ruiz", avatar: "/avatars/carlos.png" },
    internetStatus: "Exposed",
    status: "Assigned",
    severity: "Critical",
    source: "SOC",
    firstSeen: "02 Oct 2024 11:30:00",
    lastSeen: "12 Oct 2024 13:00:00",
    riskLevel: "Critical",
    responsibility: "SOC",
    resolvingGroup: "Hacking",
    businessUnit: "BU1",
    criticalAsset: true,
    regulation: "Reg1",
    riskState: "Open",
  },
  {
    id: 8,
    finding: "CVE-2024-5005",
    asset: { name: "AP_PORTAL_TA", logo: "/ap_corp.png" },
    software:
      "AP_PORTAL_TA suffers from an insecure deserialization vulnerability.",
    owner: { name: "Sofia Torres", avatar: "/avatars/sofia.png" },
    internetStatus: "None",
    status: "Accepted",
    severity: "Medium",
    source: "DevSecOps",
    firstSeen: "03 Oct 2024 15:45:00",
    lastSeen: "09 Oct 2024 17:20:00",
    riskLevel: "Medium",
    responsibility: "DevSecOps",
    resolvingGroup: "DevSecOps",
    businessUnit: "BU2",
    criticalAsset: false,
    regulation: "Reg2",
    riskState: "Closed",
  },
  // ...add more rows as needed
];

export const filterOptions = {
  riskLevel: ["Critical", "High", "Medium", "Low"],
  asset: ["AP_CORP_PORTAL", "AP_PORTAL_TA", "SAP System"],
  responsibility: ["SOC", "Hacking", "DevSecOps"],
  resolvingGroup: ["DevSecOps", "Hacking"],
  businessUnit: ["BU1", "BU2"],
  internetStatus: ["Exposed", "Locked", "Activated", "None"],
  criticalAsset: ["Yes", "No"],
  regulation: ["Reg1", "Reg2"],
  riskState: ["Open", "Closed"],
};
